#+TITLE: nodehttpd
#+author: Tim Hawes
* nodehttpd
** About
This is a simple httpd server written in NodeJS for the purposes of learning Javascript language using functional programming principles without any additional libraries.
** How to run
1. Clone the repo.
2. ~cd nodehttpd && npm run run~
3. Open at [[http://localhost:3000][http://localhost:3000]] with curl or a web browser.
** Lessons learned
*** Convert an array to a dictionary
The ~http~ module that is part of NodeJS core puts the request object's data such as ~host~, ~user-agent~, etc. in an array, such as:
#+begin_src js
req.rawHeaders;
["Host", "localhost:3000", "user-agent", "FireFox blah blah blah", ...]
#+end_src
making retrieving the data a bit tricky. What we need is to convert this array into a dictionary, so then all we need to get the user-agent is:
#+begin_src js
const headers = arrayToDict(req.rawHeaders);
console.log(headers['user-agent']);
#+end_src
In order to stay true to functional programming principles, ~arrayToDict~ needs to not change the original values of ~req.rawHeaders~. The end result involves cloning the array, and feeding it recursively into itself until there are no more values left in the array to parse. Here is the function:
#+begin_src js
// Array to dictionary
const arrayToDict = (array, data = {}) => {
  let newArray = [...array]
  let key = newArray.shift();
  if (key != undefined) {
    data[key] = newArray.shift();
  }
  if (newArray.length === 0) {
    return data;
  } else {
    return arrayToDict(newArray, data);
  }
};
#+end_src
** License
MIT License

Copyright (c) 2022 Tim Hawes

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
